-- phpMyAdmin SQL Dump
-- version 4.3.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Sep 19, 2018 at 07:23 PM
-- Server version: 5.6.24
-- PHP Version: 5.5.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `xemay`
--

-- --------------------------------------------------------

--
-- Table structure for table `carts`
--

CREATE TABLE IF NOT EXISTS `carts` (
  `id` int(11) NOT NULL,
  `id_users` int(11) NOT NULL,
  `days` date NOT NULL,
  `id_products` int(11) NOT NULL,
  `sl` int(11) NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `carts`
--

INSERT INTO `carts` (`id`, `id_users`, `days`, `id_products`, `sl`, `status`) VALUES
(23, 8, '2018-08-17', 315, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(26, 8, '2018-08-17', 157, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(27, 8, '2018-08-17', 234, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(28, 8, '2018-09-10', 0, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(29, 8, '2018-09-10', 0, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(30, 8, '2018-09-10', 0, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(31, 0, '2018-09-10', 0, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(32, 8, '2018-09-10', 0, 1, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng'),
(34, 8, '2018-09-12', 232, 0, 'ÃÃ£ nháº­n Ä‘Æ¡n hÃ ng');

-- --------------------------------------------------------

--
-- Table structure for table `caterogies`
--

CREATE TABLE IF NOT EXISTS `caterogies` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `order` int(11) NOT NULL,
  `hide` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `caterogies`
--

INSERT INTO `caterogies` (`id`, `name`, `order`, `hide`) VALUES
(1, 'Khuyến Mãi', 1, 0),
(2, 'Xe Tay Ga', 2, 0),
(3, 'Xe Số', 3, 0);

-- --------------------------------------------------------

--
-- Table structure for table `feedbacks`
--

CREATE TABLE IF NOT EXISTS `feedbacks` (
  `id` int(11) NOT NULL,
  `subject` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `feedbacks`
--

INSERT INTO `feedbacks` (`id`, `subject`, `content`, `status`) VALUES
(4, '1. Pháº£n há»“i vá» thÃ¡i Ä‘á»™ phá»¥c vá»¥', '<p>phá»¥c vá»¥ k&eacute;m</p>\r\n', 'ÄÃ£ Nháº­n ThÃ´ng Tin');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `price` int(10) NOT NULL,
  `img` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `detail` text COLLATE utf8_unicode_ci NOT NULL,
  `id_cate` int(11) NOT NULL,
  `hide` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=316 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `price`, `img`, `detail`, `id_cate`, `hide`) VALUES
(157, 'HonDa Xe Ga 01', 150000, 'honda-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(158, 'HonDa Xe Ga 02', 150000, 'honda-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(159, 'HonDa Xe Ga 03', 150000, 'honda-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(161, 'HonDa Xe Ga 05', 150000, 'honda-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(162, 'HonDa Xe Ga 06', 150000, 'honda-xega (6).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(163, 'HonDa Xe Ga 07', 150000, 'honda-xega (7).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(164, 'HonDa Xe Ga 08', 150000, 'honda-xega (8).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(165, 'HonDa Xe Ga 09', 150000, 'honda-xega (9).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(166, 'HonDa Xe Ga 10', 150000, 'honda-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(167, 'HonDa Xe Ga 11', 150000, 'honda-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(168, 'HonDa Xe Ga 12', 150000, 'honda-xega (8).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(169, 'HonDa Xe Ga 13', 150000, 'honda-xega (7).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(170, 'HonDa Xe Ga 14', 150000, 'honda-xega (6).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(171, 'HonDa Xe Ga 15', 150000, 'honda-xega (9).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(173, 'SuZuKi Xe Ga 02', 150000, 'suzuki-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(174, 'SuZuKi Xe Ga 03', 150000, 'suzuki-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(175, 'SuZuKi Xe Ga 04', 150000, 'suzuki-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(176, 'SuZuKi Xe Ga 05', 150000, 'suzuki-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(177, 'SuZuKi Xe Ga 06', 150000, 'suzuki-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(178, 'SuZuKi Xe Ga 07', 150000, 'suzuki-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(179, 'SuZuKi Xe Ga 08', 150000, 'suzuki-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(180, 'SuZuKi Xe Ga 09', 150000, 'suzuki-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(181, 'SuZuKi Xe Ga 10', 150000, 'suzuki-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(182, 'SuZuKi Xe Ga 11', 150000, 'suzuki-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(183, 'SuZuKi Xe Ga 12', 150000, 'suzuki-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(184, 'SuZuKi Xe Ga 13', 150000, 'suzuki-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(185, 'SuZuKi Xe Ga 14', 150000, 'suzuki-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(186, 'SuZuKi Xe Ga 15', 150000, 'suzuki-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(187, 'Sym Xe Ga 01', 150000, 'sym-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(188, 'Sym Xe Ga 02', 150000, 'sym-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(189, 'Sym Xe Ga 03', 150000, 'sym-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(191, 'Sym Xe Ga 05', 150000, 'sym-xega (5).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(192, 'Sym Xe Ga 06', 150000, 'sym-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(193, 'Sym Xe Ga 07', 150000, 'sym-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(194, 'Sym Xe Ga 08', 150000, 'sym-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(195, 'Sym Xe Ga 09', 150000, 'sym-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(196, 'Sym Xe Ga 10', 150000, 'sym-xega (5).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(197, 'Sym Xe Ga 11', 150000, 'sym-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(198, 'Sym Xe Ga 12', 150000, 'sym-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(199, 'Sym Xe Ga 13', 150000, 'sym-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(200, 'Sym Xe Ga 14', 150000, 'sym-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(201, 'Sym Xe Ga 15', 150000, 'sym-xega (5).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(202, 'YaMaHa Xe Ga 01', 150000, 'yamaha-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(203, 'YaMaHa Xe Ga 02', 150000, 'yamaha-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(204, 'YaMaHa Xe Ga 03', 150000, 'yamaha-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(205, 'YaMaHa Xe Ga 04', 150000, 'yamaha-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(206, 'YaMaHa Xe Ga 05', 150000, 'yamaha-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(207, 'YaMaHa Xe Ga 06', 150000, 'yamaha-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(208, 'YaMaHa Xe Ga 07', 150000, 'yamaha-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(209, 'YaMaHa Xe Ga 08', 150000, 'yamaha-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(210, 'YaMaHa Xe Ga 09', 150000, 'yamaha-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(211, 'YaMaHa Xe Ga 10', 150000, 'yamaha-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(212, 'YaMaHa Xe Ga 11', 150000, 'yamaha-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(213, 'YaMaHa Xe Ga 12', 150000, 'yamaha-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(214, 'YaMaHa Xe Ga 13', 150000, 'yamaha-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(215, 'YaMaHa Xe Ga 14', 150000, 'yamaha-xega (2).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(216, 'YaMaHa Xe Ga 15', 150000, 'yamaha-xega (3).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(218, 'Khuyến Mãi 01', 70000, 'khuyenmai (1).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(219, 'Khuyến Mãi 02', 70000, 'khuyenmai (2).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(220, 'Khuyến Mãi 03', 70000, 'khuyenmai (3).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(221, 'Khuyến Mãi 04', 70000, 'khuyenmai (4).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(222, 'Khuyến Mãi 05', 70000, 'khuyenmai (5).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(223, 'Khuyến Mãi 06', 70000, 'khuyenmai (6).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(224, 'Khuyến Mãi 07', 70000, 'khuyenmai (1).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(225, 'Khuyến Mãi 08', 70000, 'khuyenmai (2).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(226, 'Khuyến Mãi 09', 70000, 'khuyenmai (3).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(227, 'Khuyến Mãi 10', 70000, 'khuyenmai (4).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(228, 'Khuyến Mãi 11', 70000, 'khuyenmai (5).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(229, 'Khuyến Mãi 12', 70000, 'khuyenmai (6).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(230, 'Khuyến Mãi 13', 70000, 'khuyenmai (1).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(231, 'Khuyến Mãi 14', 70000, 'khuyenmai (2).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(232, 'Khuyến Mãi 15', 70000, 'khuyenmai (3).jpg', 'Với nhu cầu thuê xe của quý khách hàng tăng cao, cửa hàng chúng tôi đã đưa ra một số chương trình khuyến mãi đặc biệt dành cho một số sản phẩm.', 1, 0),
(234, 'HonDa Xe Số 01', 100000, 'honda-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(235, 'HonDa Xe Số 02', 100000, 'honda-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(236, 'HonDa Xe Số 03', 100000, 'honda-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(237, 'HonDa Xe Số 04', 100000, 'honda-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(238, 'HonDa Xe Số 05', 100000, 'honda-xeso (5).jpg', '<p>CHO THU&Ecirc; XE WAVE RSX, S110<br />\r\nKiểu xe:&nbsp;Gear 4 stroke&nbsp;<br />\r\nHiệu xe:&nbsp;Honda&nbsp;<br />\r\nGi&aacute; thu&ecirc; từ:&nbsp;70.000 VNĐ&nbsp;&nbsp;</p>\r\n\r\n<p><strong>Thủ tục gồm :&nbsp;</strong></p>\r\n\r\n<p>- Xem qua giấy tờ t&ugrave;y th&acirc;n bản gốc như&nbsp;<strong>CMND hoặc&nbsp;Passport, hộ khẩu ... v&agrave;&nbsp;bằng l&aacute;i xe</strong>&nbsp;( Sau&nbsp;đ&oacute; giữ lại 1 loại giấy tờ&nbsp;)</p>\r\n\r\n<p>- Tiền đặt cọc : 2 triệu</p>\r\n\r\n<p>- Gi&aacute; thu&ecirc; ng&agrave;y : 100k/ng&agrave;y (Giảm 10% từ 10 ng&agrave;y trở l&ecirc;n)</p>\r\n\r\n<p><strong>- Gi&aacute; thu&ecirc; th&aacute;ng 2,0 triệu</strong></p>\r\n\r\n<p><strong>&nbsp;L<strong>i&ecirc;n hệ :&nbsp;</strong></strong>120 L&yacute; Thường Kiệt, Phường Hải Th&agrave;nh,Tp Đồng Hới, Quảng B&igrave;nh</p>\r\n\r\n<p><strong><strong>Mr T&ugrave;ng :&nbsp;</strong>094 666 6566</strong></p>\r\n\r\n<p><strong>Ms Hoa&nbsp;: 01654036388</strong></p>\r\n', 3, 0),
(239, 'HonDa Xe Số 06', 100000, 'honda-xeso (6).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(240, 'HonDa Xe Số 07', 100000, 'honda-xeso (7).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(241, 'HonDa Xe Số 08', 100000, 'honda-xeso (8).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(242, 'HonDa Xe Số 09', 100000, 'honda-xeso (9).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(244, 'HonDa Xe Số 11', 100000, 'honda-xeso (11).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(245, 'HonDa Xe Số 12', 100000, 'honda-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(246, 'HonDa Xe Số 13', 100000, 'honda-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(247, 'HonDa Xe Số 14', 100000, 'honda-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(248, 'HonDa Xe Số 15', 100000, 'honda-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(264, 'YaMaHa Xe Số 01', 100000, 'yamaha-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(265, 'YaMaHa Xe Số 02', 100000, 'yamaha-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(266, 'YaMaHa Xe Số 03', 100000, 'yamaha-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(267, 'YaMaHa Xe Số 04', 100000, 'yamaha-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(268, 'YaMaHa Xe Số 05', 100000, 'yamaha-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(269, 'YaMaHa Xe Số 06', 100000, 'yamaha-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(270, 'YaMaHa Xe Số 07', 100000, 'yamaha-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(271, 'YaMaHa Xe Số 08', 100000, 'yamaha-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(272, 'YaMaHa Xe Số 09', 100000, 'yamaha-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(273, 'YaMaHa Xe Số 10', 100000, 'yamaha-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(274, 'YaMaHa Xe Số 11', 100000, 'yamaha-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(275, 'YaMaHa Xe Số 12', 100000, 'yamaha-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(276, 'YaMaHa Xe Số 13', 100000, 'yamaha-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(277, 'YaMaHa Xe Số 14', 100000, 'yamaha-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(278, 'YaMaHa Xe Số 15', 100000, 'yamaha-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(279, 'SuZuKi Xe Số 01', 100000, 'suzuki-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(280, 'SuZuKi Xe Số 02', 100000, 'suzuki-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(281, 'SuZuKi Xe Số 03', 100000, 'suzuki-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(282, 'SuZuKi Xe Số 04', 100000, 'suzuki-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(283, 'SuZuKi Xe Số 05', 100000, 'suzuki-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(284, 'SuZuKi Xe Số 06', 100000, 'suzuki-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(285, 'SuZuKi Xe Số 07', 100000, 'suzuki-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(286, 'SuZuKi Xe Số 08', 100000, 'suzuki-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0);
INSERT INTO `products` (`id`, `name`, `price`, `img`, `detail`, `id_cate`, `hide`) VALUES
(287, 'SuZuKi Xe Số 09', 100000, 'suzuki-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(288, 'SuZuKi Xe Số 10', 100000, 'suzuki-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(290, 'SuZuKi Xe Số 12', 100000, 'suzuki-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(291, 'SuZuKi Xe Số 13', 100000, 'suzuki-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(292, 'SuZuKi Xe Số 14', 100000, 'suzuki-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(293, 'SuZuKi Xe Số 15', 100000, 'suzuki-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(294, 'Sym Xe Số 01', 100000, 'sym-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(295, 'Sym Xe Số 02', 100000, 'sym-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(296, 'Sym Xe Số 03', 100000, 'sym-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(297, 'Sym Xe Số 04', 100000, 'sym-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(298, 'Sym Xe Số 05', 100000, 'sym-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(299, 'Sym Xe Số 06', 100000, 'sym-xeso (6).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(300, 'Sym Xe Số 07', 100000, 'sym-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(301, 'Sym Xe Số 08', 100000, 'sym-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(302, 'Sym Xe Số 09', 100000, 'sym-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(303, 'Sym Xe Số 10', 100000, 'sym-xeso (4).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(304, 'Sym Xe Số 11', 100000, 'sym-xeso (5).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(305, 'Sym Xe Số 12', 100000, 'sym-xeso (6).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(306, 'Sym Xe Số 13', 100000, 'sym-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(307, 'Sym Xe Số 14', 100000, 'sym-xeso (2).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(308, 'Sym Xe Số 15', 100000, 'sym-xeso (3).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(309, 'HonDa Xe Ga 04', 150000, 'honda-xega (4).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(312, 'SuZuKi Xe Ga 01', 150000, 'suzuki-xega (1).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(313, 'Sym Xe Ga 05', 150000, 'sym-xega (5).jpg', 'Xe tay ga đã trở nên khá phổ biến trên đường phố hiện nay tại Việt Nam. Không khó để có thể bắt gặp một chiếc xe tay ga đang lưu thông trên đường phố, thậm chí tỉ lệ sử dụng xe tay ga tại các thành phố lớn đã vượt qua xe số. Với kiểu dáng sang trong, dễ lái, xe tay ga đã thu hút được rất nhiều sự quan tâm từ khách hàng, nhưng đi kèm với đó là một số nhược điểm khiến khách hàng khó chịu.', 2, 0),
(314, 'SuZuKi Xe Số 11', 100000, 'suzuki-xeso (1).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0),
(315, 'HonDa Xe Số 10', 100000, 'honda-xeso (10).jpg', ' Xe máy số cũng là một trong những phương tiện di chuyển rất phổ biến hiện nay. Thậm chí ở một số quốc gia, số lượng xe gắn máy còn vượt trội hơn rất nhiều so với các loại xe ô tô và phương tiện công công, Việt Nam cũng là một trong số những quốc gia như vậy. Bên cạnh những ưu điểm như sử dụng tiện lợi, điều khiển dễ dàng, phù hợp với nhiều loại địa hình và đường xá, những chiếc xe máy còn có giá thành rẻ hơn cũng như mức tiêu thụ nhiên liệu thấp hơn khá nhiều so với xe tay ga.', 3, 0);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `phone` varchar(13) COLLATE utf8_unicode_ci NOT NULL,
  `role` int(11) NOT NULL,
  `cmnd` varchar(13) COLLATE utf8_unicode_ci NOT NULL,
  `gplx` varchar(13) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `email`, `phone`, `role`, `cmnd`, `gplx`) VALUES
(7, 'h', 'e10adc3949ba59abbe56e057f20f883e', 'a@gmail.com', '01654036376', 0, '142222510114', '14379896655'),
(8, 'hoa', 'e10adc3949ba59abbe56e057f20f883e', 'phamhoaqqb98@gmail.com', '01654036388', 1, '142222511111', '14379899799'),
(9, 'admin', '0192023a7bbd73250516f069df18b500', 'phamhoaqqb98@gmail.com', '01654036388', 1, '142222511111', '14379899799'),
(10, 'hÃ´ng', 'fcea920f7412b5da7be0cf42b8c93759', 'phamhoaqqb98@gmail.com', '0123456789', 0, '167586585', '245678456'),
(11, '', 'd41d8cd98f00b204e9800998ecf8427e', '', '', 0, '', ''),
(12, 'hanh', 'fcea920f7412b5da7be0cf42b8c93759', 'pham@gmail.com', '01685863997', 0, '168589368', '268969595'),
(13, 'phuoc', 'fcea920f7412b5da7be0cf42b8c93759', 'phuopc@gmail.com', '01645895378', 0, '866068468', '14379899799'),
(14, 'trang', 'fcea920f7412b5da7be0cf42b8c93759', 'tranmgtranf@gmail.com', '08683683544', 0, '367289597', '467926859123');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `carts`
--
ALTER TABLE `carts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `caterogies`
--
ALTER TABLE `caterogies`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `feedbacks`
--
ALTER TABLE `feedbacks`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `carts`
--
ALTER TABLE `carts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=35;
--
-- AUTO_INCREMENT for table `caterogies`
--
ALTER TABLE `caterogies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `feedbacks`
--
ALTER TABLE `feedbacks`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=316;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=15;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
